### ISSUE TITLE
No se puede editar horario de cátedra

### ISSUE THREAD

**Issue by negebauer** [nicogeb/IIC2143IngenieriaDeSoftware#27]
@dacasas Tira este error

```
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
    at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1771)
    ... 45 more
Caused by: java.lang.NullPointerException
    at frontend.admin.AScheduleViewController.setUp(AScheduleViewController.java:203)
    at frontend.others.ViewUtilities.openNewView(ViewUtilities.java:84)
    at frontend.admin.AICourseManagerLectureEditingViewController.btnSeeSchedule_Pressed(AICourseManagerLectureEditingViewController.java:115)
    ... 55 more
```

Aquí

```
btnSaveSchedule.getScene().getWindow().setOnCloseRequest(new EventHandler<WindowEvent>() {
          public void handle(WindowEvent we) {
              btnSaveSchedule_Pressed();
          }
        });
```

**Comment by negebauer** [comment]
@dacasas 
Precioso

<img width="462" alt="captura de pantalla 2015-12-04 a las 02 17 16" src="https://cloud.githubusercontent.com/assets/11860880/11582399/2db32384-9a2d-11e5-9eae-e358163dff89.png">
